export {default as NewGame} from './modularized-game'
export {default as SourceChannel} from './channel'
export {default as TargetChannel} from './target-channel'
export {default as Turntable} from './turntable'
export {default as VolumeFader} from './vol-fader'
export {default as PitchFader} from './pitch-fader'
export {default as Tutorial} from './tutorial'
export {default as TutorialMode} from './tutorial-mode'
export {default as Game} from './game'
//export {default as Cube} from './cube'
//export {default as CardAnime} from './card-anime'
export {default as About} from './about'
export {default as Homepage} from './homepage'
export {default as Navbar} from './navbar'
export {default as UserHome} from './user-home'
export {Login, Signup} from './auth-form'
